/**
 * ExplanationPanel - Displays LLM-generated margin call explanation
 */

import { Lightbulb, AlertTriangle, CheckCircle, FileText, Brain } from 'lucide-react';
import { formatDate } from '../../utils/formatting';
import type { MarginCallExplanation } from '../../types/calculations';

interface ExplanationPanelProps {
  explanation: MarginCallExplanation;
}

export function ExplanationPanel({ explanation }: ExplanationPanelProps) {
  const {
    narrative,
    key_factors,
    risk_assessment,
    next_steps,
    citations,
    generated_at,
    llm_model,
  } = explanation;

  return (
    <div className="bg-white rounded-lg border border-gray-200 shadow-sm">
      {/* Header */}
      <div className="px-6 py-4 border-b border-gray-200 bg-gradient-to-r from-purple-50 to-blue-50">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-purple-100">
              <Brain className="w-5 h-5 text-purple-600" />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-gray-800">AI-Generated Explanation</h3>
              <p className="text-sm text-gray-600">
                Generated by {llm_model} on {formatDate(generated_at)}
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="p-6 space-y-6">
        {/* Narrative */}
        <div>
          <h4 className="text-sm font-semibold text-gray-700 mb-3 flex items-center gap-2">
            <Lightbulb className="w-4 h-4 text-yellow-500" />
            Summary
          </h4>
          <div className="prose prose-sm max-w-none text-gray-700 whitespace-pre-line">
            {narrative}
          </div>
        </div>

        {/* Key Factors */}
        {key_factors && key_factors.length > 0 && (
          <div className="pt-4 border-t border-gray-200">
            <h4 className="text-sm font-semibold text-gray-700 mb-3 flex items-center gap-2">
              <CheckCircle className="w-4 h-4 text-green-500" />
              Key Factors
            </h4>
            <ul className="space-y-2">
              {key_factors.map((factor, index) => (
                <li key={index} className="flex items-start gap-2 text-sm text-gray-700">
                  <span className="flex-shrink-0 w-5 h-5 rounded-full bg-blue-100 text-blue-600 text-xs font-semibold flex items-center justify-center mt-0.5">
                    {index + 1}
                  </span>
                  <span>{factor}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Risk Assessment */}
        {risk_assessment && (
          <div className="pt-4 border-t border-gray-200">
            <h4 className="text-sm font-semibold text-gray-700 mb-3 flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-orange-500" />
              Risk Assessment
            </h4>
            <p className="text-sm text-gray-700 whitespace-pre-line">{risk_assessment}</p>
          </div>
        )}

        {/* Next Steps */}
        {next_steps && (
          <div className="pt-4 border-t border-gray-200">
            <h4 className="text-sm font-semibold text-gray-700 mb-3 flex items-center gap-2">
              <CheckCircle className="w-4 h-4 text-blue-500" />
              Recommended Next Steps
            </h4>
            <p className="text-sm text-gray-700 whitespace-pre-line">{next_steps}</p>
          </div>
        )}

        {/* Citations */}
        {citations && Object.keys(citations).length > 0 && (
          <div className="pt-4 border-t border-gray-200">
            <h4 className="text-sm font-semibold text-gray-700 mb-3 flex items-center gap-2">
              <FileText className="w-4 h-4 text-gray-500" />
              CSA Document Citations
            </h4>
            <div className="space-y-2">
              {Object.entries(citations).map(([clause, page], index) => (
                <div key={index} className="flex items-start gap-2 text-sm">
                  <span className="flex-shrink-0 text-gray-500">•</span>
                  <div className="flex-1">
                    <span className="text-gray-700">{clause}</span>
                    {page !== null && (
                      <span className="ml-2 text-gray-500">(Page {page})</span>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
